# Generated by Django 5.0.6 on 2024-06-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(verbose_name='Tuổi'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Màu Sắc'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã Thú Cưng'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='length',
            field=models.IntegerField(verbose_name='Chiều Cao'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Tên Thú Cưng'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('cat', 'cat'), ('dog', 'dog')], max_length=3, verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.FloatField(verbose_name='Cân Nặng'),
        ),
    ]
